# Generated by Django 3.1.2 on 2020-11-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_birth',
            field=models.EmailField(max_length=254),
        ),
    ]
