# Generated by Django 3.1.2 on 2020-11-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_auto_20201102_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='passing_year',
            field=models.DateField(),
        ),
    ]
