# Generated by Django 3.1.2 on 2020-11-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_auto_20201102_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
