# Generated by Django 3.1.2 on 2020-11-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_auto_20201102_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
